ARG IMAGE
FROM $IMAGE
MAINTAINER Romain Beauxis <toots@rastageeks.org>

ARG COMPILER
ARG SYSTEM

RUN sed -i /etc/apt/sources.list -e 's#jessie#testing#g' && (apt-get update || true) && \
      apt-get install -y --force-yes gawk aspcud binutils automake opam && \
      apt-get -y --force-yes autoremove && apt-get -y --force-yes clean

WORKDIR /usr/src/mxe
RUN git pull origin master && make cc

RUN useradd -g staff --create-home opam
USER opam

RUN opam init --auto --compiler=$COMPILER

WORKDIR /home/opam/opam-cross-windows

ADD packages/ /home/opam/opam-cross-windows/packages

USER root

RUN chown -R opam /home/opam/opam-cross-windows

USER opam

RUN opam repository add windows /home/opam/opam-cross-windows

RUN if [ "$SYSTEM" = "x64" ]; then \
      export TOOLPREF64=/usr/src/mxe/usr/bin/x86_64-w64-mingw32.static- && \
      eval $(opam config env) && opam update && \
      opam install -y ocaml-windows; \
    fi

RUN if [ "$SYSTEM" = "x86" ]; then \
      export TOOLPREF32=/usr/src/mxe/usr/bin/i686-w64-mingw32.static- && \
      eval $(opam config env) && opam update && \
      opam install -y ocaml-windows; \
    fi
